- name: Register Demo / Dependency Task 
  hosts: servera*
  gather_facts: false
  become: true
  tasks:
    - name: Install Apache Httpd Server
      ansible.builtin.dnf:
        name: httpd
        state: present
      register: captured

    - name: Print Captured Complete Output
      ansible.builtin.debug:
        msg: "{{ captured }}"

    - name: Print Captured Complete Output
      ansible.builtin.debug:
        msg: "{{ captured.changed }}"

    # - name: Deploy Web Page
    #   ansible.builtin.copy:
    #     content: "Index Page"
    #     dest: /var/www/html/index.html
    #     mode: 0644

    - name: Start Web Service
      ansible.builtin.service:
        name: httpd
        state: started
      when: captured.changed == true
